name: Deploy

on:
  release:
    types: [published]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Deploy to Render
              env:
                deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
              run: |
                curl "$deploy_url"